server:
  port: ${SERVER_PORT}

spring:
  application:
    name: payments

  webflux:
    multipart:
      max-in-memory-size: ${SPRING_WEBFLUX_MULTIPART_MAX_IN_MEMORY_SIZE}
      max-disk-usage-per-part: ${SPRING_WEBFLUX_MULTIPART_MAX_DISK_USAGE_PER_PART}
      max-parts: ${SPRING_WEBFLUX_MULTIPART_MAX_PARTS}

  http:
    codecs:
      max-in-memory-size: ${SPRING_CODEC_MAX_IN_MEMORY_SIZE}

logging:
  level:
    ru:
      practicum: ${LOGGING_PRACTICUM_LEVEL}
