spring:
  application:
    name: my-market-app

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: ${DATASOURCE_SCHEMA_NAME}

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}

logging:
  level:
    ru:
      practicum: ${LOGGING_PRACTICUM_LEVEL}
    org.hibernate.SQL: debug

image:
  path: ${IMAGE_PATH}
