DATASOURCE_SCHEMA_NAME: market_app
SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres?currentSchema=${DATASOURCE_SCHEMA_NAME}
SPRING_DATASOURCE_USERNAME: postgres
SPRING_DATASOURCE_PASSWORD: postgres

LOGGING_PRACTICUM_LEVEL: DEBUG

SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB

IMAGE_PATH: images
