SERVER_PORT: 8080

DATASOURCE_SCHEMA_NAME: market_app

SPRING_R2DBC_URL: r2dbc:postgresql://localhost:5432/postgres?currentSchema=${DATASOURCE_SCHEMA_NAME}
SPRING_R2DBC_USERNAME: postgres
SPRING_R2DBC_PASSWORD: postgres

SPRING_LIQUIBASE_URL: jdbc:postgresql://localhost:5432/postgres?currentSchema=${DATASOURCE_SCHEMA_NAME}
SPRING_LIQUIBASE_USER: postgres
SPRING_LIQUIBASE_PASSWORD: postgres

LOGGING_PRACTICUM_LEVEL: DEBUG

SPRING_WEBFLUX_MULTIPART_MAX_DISK_USAGE_PER_PART: 10MB
SPRING_WEBFLUX_MULTIPART_MAX_IN_MEMORY_SIZE: 1MB
SPRING_WEBFLUX_MULTIPART_MAX_PARTS: 256
SPRING_CODEC_MAX_IN_MEMORY_SIZE: 2MB

REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379
REDIS_TTL: PT1M

IMAGE_PATH: images

PAYMENTS_BASE_URL: 'http://localhost:8081'
